import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header, Footer } from "../components/sections";

const IRANSansX = localFont({
  src: [
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Thin.ttf",
      weight: "100"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-UltraLight.ttf",
      weight: "200"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Light.ttf",
      weight: "300"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Regular.ttf",
      weight: "400"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Medium.ttf",
      weight: "500"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-DemiBold.ttf",
      weight: "600"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Bold.ttf",
      weight: "700"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-ExtraBold.ttf",
      weight: "800"
    },
    {
      path: "../../public/fonts/IRANSansX/IRANSansX-Black.ttf",
      weight: "900"
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IRANSansX.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
